config/routes.rb
routes = lambda do
  get '/paypal', :to => "paypal#express", :as => :paypal_express
  get '/paypal/confirm', :to => "paypal#confirm", :as => :confirm_paypal
  get '/paypal/cancel', :to => "paypal#cancel", :as => :cancel_paypal
  get '/paypal/notify', :to => "paypal#notify", :as => :notify_paypal

  namespace :admin do
    # Using :only here so it doesn't redraw those routes
    resources :orders, :only => [] do
      resources :payments, :only => [] do
        member do
          get 'paypal_refund'
          post 'paypal_refund'
        end
      end
    end
  end
end

if Spree::Core::Engine.respond_to?(:add_routes)
  Spree::Core::Engine.add_routes(&routes)
else
  Spree::Core::Engine.routes.draw(&routes)
end

app/views/spree/checkout/payment/_paypal.html.erb
<div class="row paypal-form" id="paypal-form">
  <div class="fieldset">
    <div class="small-12 large-7 columns description">
    <p><span><%=Spree.t(:paypal_redirect)%></span></p>
    </div>
    <div class="small-12 large-5 columns">
      <div class="form-buttons" data-hook="buttons">
        <%= link_to(Spree.t(:paypal_submit), paypal_express_url(:payment_method_id => payment_method.id), :method => :post, class: "button primary", :id => "paypal_button") %>
      </div>
    </div>
  </div>
</div>


<script>
  var setPaypalExpress = function(e) {
    SpreePaypalExpress.paymentMethodID = "<%= payment_method.id %>"
  };
  document.addEventListener("DOMContentLoaded", setPaypalExpress);
  document.addEventListener("page:load", setPaypalExpress);
</script>